CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_MAX_PAIRED=4

# Turn on mouse key
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y

# Enable MLX90393
CONFIG_PINCTRL=y
CONFIG_GPIO=y
CONFIG_SPI=y
# CONFIG_INPUT_LOG_LEVEL_DBG=y
CONFIG_USB_DEVICE_HID=y
CONFIG_USB_HID_DEVICE_COUNT=2
CONFIG_ZMK_HID_JOYSTICK=y
CONFIG_ZMK_HID_JOYSTICK_LOG_LEVEL_DBG=y

# +8 dBm
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Go to sleep after 30 mins (30*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
CONFIG_ZMK_SLEEP=y
